[package]
name = "scraping"
edition = "2021"

[dependencies]
prest = { version = "0.5", path = "../../" }
reqwest = { version = "0.12", default-features=false, features = ["rustls-tls"] }
scraper = "0.22"
