[package]
name = "scraping"
edition = "2021"

[dependencies]
prest = { path = "../../", version = "0.4" }
reqwest = { version = "0.12", default-features=false, features = ["rustls-tls"] }
scraper = "0.22"
