[workspace]

[package]
name = "host"
edition = "2021"

[[bin]]
name = "host"
path = "./main.rs"

[features]
default = ["std"]
try-runtime = []
std = [
	"codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-runtime/std",
	"scale-info/std",
    "pallet-transaction-payment/std",
    "pallet-balances/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
]

[dependencies]
runtime = { path = "../runtime" }
#prest = { path = "../../", version = "0.4" }

getrandom = { version = "0.2", features = ["js"] }

codec = { package = "parity-scale-codec", version = "3.6", features = ["derive"] }
scale-info = { version = "2.11.1", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
frame-executive = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.0", features = ["derive"] }

sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sc-chain-spec = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sc-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[build-dependencies]
polkadot-sdk = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "stable2407", features = ["substrate-build-script-utils"] }
