[package]
name = "todo-pwa"
edition = "2021"

[dependencies]
prest = { version = "0.5", path = "../../" }
wasm-bindgen = "0.2"

[build-dependencies]
prest-build = { version = "0.4", path = "../../build" }

