[package]
name = "todo-pwa-auth-sync"
edition = "2021"

[dependencies]
prest = { path = "../../", version = "0.4", features = ["auth"] }
wasm-bindgen = "0.2"

[build-dependencies]
prest-build = "0.2"
